// Auto-generated IDL type definition for Proof of Inference.
// In production, this is generated by `anchor build` and imported from
// `target/idl/proof_of_inference.json`. This hand-written version matches
// the on-chain program and allows the SDK to work before the first build.

export type ProofOfInferenceIDL = {
  version: "0.1.0";
  name: "proof_of_inference";
  instructions: any[];
  accounts: any[];
  types: any[];
  events: any[];
  errors: any[];
};

export const IDL = {
  address: "CCdibNmqNCG58v4fVjAKvwXora2ekGYToUTTQF6QVmuh",
  version: "0.1.0",
  name: "proof_of_inference",
  instructions: [
    {
      name: "registerModel",
      accounts: [
        { name: "modelRegistry", isMut: true, isSigner: false },
        { name: "mxeConfig", isMut: false, isSigner: false },
        { name: "owner", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "weightCommitment", type: { array: ["u8", 32] } },
        { name: "modelName", type: "string" },
        { name: "modelVersion", type: "u16" },
        { name: "modelType", type: { defined: "ModelType" } },
      ],
    },
    {
      name: "updateModel",
      accounts: [
        { name: "modelRegistry", isMut: true, isSigner: false },
        { name: "owner", isMut: false, isSigner: true },
      ],
      args: [
        { name: "active", type: { option: "bool" } },
        { name: "mxeConfig", type: { option: "publicKey" } },
        { name: "modelVersion", type: { option: "u16" } },
      ],
    },
    {
      name: "requestInference",
      accounts: [
        { name: "modelRegistry", isMut: false, isSigner: false },
        { name: "verifiedInference", isMut: true, isSigner: false },
        { name: "requester", isMut: true, isSigner: true },
        { name: "requesterToken", isMut: true, isSigner: false },
        { name: "protocolFeeVault", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "encryptedInput", type: "bytes" },
        { name: "nonce", type: { array: ["u8", 32] } },
      ],
    },
    {
      name: "callbackVerifiedInference",
      accounts: [
        { name: "verifiedInference", isMut: true, isSigner: false },
        { name: "modelRegistry", isMut: true, isSigner: false },
        { name: "arciumAuthority", isMut: false, isSigner: true },
      ],
      args: [
        { name: "outputData", type: "bytes" },
        { name: "cluster", type: "publicKey" },
        { name: "nodeCount", type: "u8" },
      ],
    },
    {
      name: "failInference",
      accounts: [
        { name: "verifiedInference", isMut: true, isSigner: false },
        { name: "arciumAuthority", isMut: false, isSigner: true },
      ],
      args: [{ name: "reason", type: "string" }],
    },
    {
      name: "checkVerification",
      accounts: [
        { name: "verifiedInference", isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "ModelRegistry",
      type: {
        kind: "struct",
        fields: [
          { name: "owner", type: "publicKey" },
          { name: "weightCommitment", type: { array: ["u8", 32] } },
          { name: "modelName", type: "string" },
          { name: "modelVersion", type: "u16" },
          { name: "modelType", type: { defined: "ModelType" } },
          { name: "totalInferences", type: "u64" },
          { name: "createdAt", type: "i64" },
          { name: "active", type: "bool" },
          { name: "mxeConfig", type: "publicKey" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "VerifiedInference",
      type: {
        kind: "struct",
        fields: [
          { name: "model", type: "publicKey" },
          { name: "modelCommitment", type: { array: ["u8", 32] } },
          { name: "inputHash", type: { array: ["u8", 32] } },
          { name: "outputHash", type: { array: ["u8", 32] } },
          { name: "outputData", type: "bytes" },
          { name: "requester", type: "publicKey" },
          { name: "arciumCluster", type: "publicKey" },
          { name: "nodeCount", type: "u8" },
          { name: "timestamp", type: "i64" },
          { name: "status", type: { defined: "VerificationStatus" } },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  types: [
    {
      name: "ModelType",
      type: {
        kind: "enum",
        variants: [
          { name: "SentimentClassifier" },
          { name: "TextClassifier" },
          { name: "RiskScorer" },
          { name: "AnomalyDetector" },
          { name: "CustomClassifier" },
        ],
      },
    },
    {
      name: "VerificationStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Verified" },
          { name: "Failed" },
        ],
      },
    },
    {
      name: "VerificationResult",
      type: {
        kind: "struct",
        fields: [
          { name: "verified", type: "bool" },
          { name: "model", type: "publicKey" },
          { name: "modelCommitment", type: { array: ["u8", 32] } },
          { name: "nodeCount", type: "u8" },
          { name: "timestamp", type: "i64" },
          { name: "cluster", type: "publicKey" },
        ],
      },
    },
  ],
  events: [
    {
      name: "ModelRegistered",
      fields: [
        { name: "model", type: "publicKey", index: false },
        { name: "owner", type: "publicKey", index: false },
        { name: "weightCommitment", type: { array: ["u8", 32] }, index: false },
        { name: "modelName", type: "string", index: false },
        { name: "modelVersion", type: "u16", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "ModelUpdated",
      fields: [
        { name: "model", type: "publicKey", index: false },
        { name: "active", type: "bool", index: false },
        { name: "modelVersion", type: "u16", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "InferenceRequested",
      fields: [
        { name: "model", type: "publicKey", index: false },
        { name: "requester", type: "publicKey", index: false },
        { name: "inference", type: "publicKey", index: false },
        { name: "inputHash", type: { array: ["u8", 32] }, index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "InferenceVerified",
      fields: [
        { name: "model", type: "publicKey", index: false },
        { name: "inference", type: "publicKey", index: false },
        { name: "nodeCount", type: "u8", index: false },
        { name: "cluster", type: "publicKey", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "InferenceFailed",
      fields: [
        { name: "inference", type: "publicKey", index: false },
        { name: "model", type: "publicKey", index: false },
        { name: "reason", type: "string", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: "ModelNameTooLong", msg: "Model name exceeds maximum length of 64 bytes" },
    { code: 6001, name: "ModelInactive", msg: "Model is not active and cannot accept inference requests" },
    { code: 6002, name: "UnauthorizedCallback", msg: "Only the Arcium callback authority can finalize inferences" },
    { code: 6003, name: "InferenceNotPending", msg: "Inference is not in Pending status" },
    { code: 6004, name: "OutputDataTooLarge", msg: "Output data exceeds maximum allowed size" },
    { code: 6005, name: "InvalidNodeCount", msg: "Node count must be greater than zero" },
    { code: 6006, name: "TokenOwnerMismatch", msg: "Token account owner does not match requester" },
    { code: 6007, name: "ModelMismatch", msg: "Model registry does not match the inference record" },
  ],
};
