//! Writes `arcium_callback_authority_pubkey.rs` into `OUT_DIR` so the program
//! bakes in the allowed Arcium callback signer.
//!
//! - **`MXE_CALLBACK_AUTHORITY`** — deterministic PDA owned by the Arcium MXE
//!   program: `find_program_address([b"ArciumSignerAccount"], MXE_PROGRAM_ID)`.
//!   This is the **only** callback signer a release build accepts. The MXE
//!   program signs with this PDA via `invoke_signed` when it CPIs into us at
//!   the end of every computation. Override with `POI_MXE_SIGN_PDA=<base58>`
//!   before `anchor build` whenever you redeploy the MXE. Recompute with:
//!     `solana find-program-derived-address <MXE_PROGRAM_ID> string:ArciumSignerAccount`
//!
//! - **`ARCIUM_CALLBACK_AUTHORITY`** — an off-chain keypair that can finalize
//!   inferences *without* an MPC computation. This exists purely so the
//!   integration tests can drive the callback path on a local validator, and it
//!   is compiled in **only** under the `test-callback` cargo feature:
//!
//!       anchor build -- --features test-callback
//!
//!   Never enable that feature for a deployed artifact. Anyone holding the
//!   keypair could forge `Verified` attestations with arbitrary outputs and
//!   node counts, which defeats the entire point of the protocol — and the
//!   default keypair is committed to this repository at
//!   `tests/fixtures/arcium_callback_authority.json`.

use std::env;
use std::fs;
use std::path::Path;
use std::str::FromStr;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=POI_ARCIUM_CALLBACK_AUTHORITY");
    println!("cargo:rerun-if-env-changed=POI_MXE_SIGN_PDA");

    // Default = sign-PDA for the MXE keypair currently checked into
    // `mxe/poi_mxe/target/deploy/poi_mxe_scaffold-keypair.json`
    // (`EFZ1VFf9ws338N9YktYuVQXB8ascEhQ3agtRvVE2rzKF`). When you redeploy the
    // MXE to a different address, recompute via:
    //   `solana find-program-derived-address <NEW_MXE_PROGRAM_ID> string:ArciumSignerAccount`
    // and override with `POI_MXE_SIGN_PDA=<base58>` before `anchor build`.
    let mxe_sign = read_pk(
        "POI_MXE_SIGN_PDA",
        "5ju1CA9CJichpT9hpgqTXsAF6tf7oLJsRUpGcP7yd3Qi",
    );

    let mut rust = format!(
        r#"// Auto-generated by build.rs — do not edit.
/// Production callback signer: deterministic PDA the Arcium MXE program signs
/// with via `invoke_signed` when its callback CPIs into us.
pub(crate) const MXE_CALLBACK_AUTHORITY: Pubkey = solana_pubkey::pubkey!("{mxe_sign}");
"#,
    );

    // Cargo exposes enabled features to build scripts as CARGO_FEATURE_<NAME>.
    if env::var_os("CARGO_FEATURE_TEST_CALLBACK").is_some() {
        let off_chain = read_pk(
            "POI_ARCIUM_CALLBACK_AUTHORITY",
            "frM1CnN1bvUDTHFSLCHQ7Mnb9PZp5u2fW7CLuWXscZM",
        );
        println!(
            "cargo:warning=`test-callback` is enabled: off-chain signer {off_chain} can finalize \
             inferences with no MPC computation. Never ship this build."
        );
        rust.push_str(&format!(
            r#"
/// Test-only off-chain callback signer. Present only under `test-callback`.
pub(crate) const ARCIUM_CALLBACK_AUTHORITY: Pubkey = solana_pubkey::pubkey!("{off_chain}");
"#,
        ));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("arcium_callback_authority_pubkey.rs");
    fs::write(&dest, rust).unwrap_or_else(|e| panic!("write {:?}: {}", dest, e));
}

fn read_pk(env_var: &str, default: &str) -> String {
    let raw = env::var(env_var).unwrap_or_else(|_| default.to_string());
    let trimmed = raw.trim().to_string();
    if trimmed.is_empty() {
        panic!("{env_var} is empty; omit it to use the default ({default})");
    }
    solana_pubkey::Pubkey::from_str(&trimmed)
        .unwrap_or_else(|_| panic!("{env_var} must be a valid base58 Solana pubkey, got {trimmed:?}"));
    trimmed
}
