//! Writes `arcium_callback_authority_pubkey.rs` into `OUT_DIR` so the program
//! bakes in the allowed Arcium callback signers.
//!
//! Two pubkeys are emitted; either is accepted by `callback_verified_inference`:
//!
//! - **`ARCIUM_CALLBACK_AUTHORITY`** — off-chain signer used exclusively by the
//!   integration tests (`tests/`) so they can invoke the callback without
//!   running a real MPC computation. Override with
//!   `POI_ARCIUM_CALLBACK_AUTHORITY=<base58>` before `anchor build`. Default
//!   matches `tests/fixtures/arcium_callback_authority.json`. **Production
//!   inferences never go through this signer** — there is no off-chain
//!   relayer; the MXE callback finalizes everything end-to-end.
//!
//! - **`MXE_CALLBACK_AUTHORITY`** — deterministic PDA owned by the Arcium MXE
//!   program: `find_program_address([b"ArciumSignerAccount"], MXE_PROGRAM_ID)`.
//!   This is the **production** callback signer — the MXE program signs with
//!   this PDA via `invoke_signed` when it CPIs into us at the end of every
//!   computation. Override with `POI_MXE_SIGN_PDA=<base58>` before
//!   `anchor build` whenever you redeploy the MXE. Recompute with:
//!     `solana find-program-derived-address <MXE_PROGRAM_ID> string:ArciumSignerAccount`

use std::env;
use std::fs;
use std::path::Path;
use std::str::FromStr;

fn main() {
    println!("cargo:rerun-if-env-changed=POI_ARCIUM_CALLBACK_AUTHORITY");
    println!("cargo:rerun-if-env-changed=POI_MXE_SIGN_PDA");

    let off_chain = read_pk(
        "POI_ARCIUM_CALLBACK_AUTHORITY",
        "frM1CnN1bvUDTHFSLCHQ7Mnb9PZp5u2fW7CLuWXscZM",
    );
    // Default = sign-PDA for the MXE keypair currently checked into
    // `mxe/poi_mxe/target/deploy/poi_mxe_scaffold-keypair.json`
    // (`EFZ1VFf9ws338N9YktYuVQXB8ascEhQ3agtRvVE2rzKF`). When you redeploy the
    // MXE to a different address, recompute via:
    //   `solana find-program-derived-address <NEW_MXE_PROGRAM_ID> string:ArciumSignerAccount`
    // and override with `POI_MXE_SIGN_PDA=<base58>` before `anchor build`.
    let mxe_sign = read_pk(
        "POI_MXE_SIGN_PDA",
        "5ju1CA9CJichpT9hpgqTXsAF6tf7oLJsRUpGcP7yd3Qi",
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("arcium_callback_authority_pubkey.rs");
    let rust = format!(
        r#"// Auto-generated by build.rs — do not edit.
/// Test-only off-chain callback signer (integration tests).
pub(crate) const ARCIUM_CALLBACK_AUTHORITY: Pubkey = solana_pubkey::pubkey!("{off_chain}");
/// Production callback signer: deterministic PDA the Arcium MXE program signs
/// with via `invoke_signed` when its callback CPIs into us.
pub(crate) const MXE_CALLBACK_AUTHORITY: Pubkey = solana_pubkey::pubkey!("{mxe_sign}");
"#,
    );

    fs::write(&dest, rust).unwrap_or_else(|e| panic!("write {:?}: {}", dest, e));
}

fn read_pk(env_var: &str, default: &str) -> String {
    let raw = env::var(env_var).unwrap_or_else(|_| default.to_string());
    let trimmed = raw.trim().to_string();
    if trimmed.is_empty() {
        panic!("{env_var} is empty; omit it to use the default ({default})");
    }
    solana_pubkey::Pubkey::from_str(&trimmed)
        .unwrap_or_else(|_| panic!("{env_var} must be a valid base58 Solana pubkey, got {trimmed:?}"));
    trimmed
}
