[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
poi_mxe_scaffold = "EFZ1VFf9ws338N9YktYuVQXB8ascEhQ3agtRvVE2rzKF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
